worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # DEVSECOPS: Ukrywanie wersji Nginxa (żeby atakujący nie wiedział, czy masz podatną wersję)
    server_tokens off;

    # DEVSECOPS: Twardy limit rozmiaru przesyłanego pliku (15 MB)
    client_max_body_size 15M;

    # DEVSECOPS: Rate Limiting - max 5 zapytań na sekundę z jednego IP (ochrona przed DoS)
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    server {
        listen 80;
        server_name localhost;

        # DEVSECOPS: Nagłówki bezpieczeństwa (Security Headers)
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;

        # Routing żądań do aplikacji React (Frontend)
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Routing żądań do mikrousługi API
        location /api/ {
            # Aktywacja Rate Limitingu dla ścieżki API
            limit_req zone=api_limit burst=10 nodelay;
            
            proxy_pass http://upload-service:8000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}