apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: secuscan-ns
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: secuscan-ns
spec:
  serviceName: "postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: fix-permissions
          image: alpine:3.19
          command: ["sh", "-c", "chown -R 70:70 /var/lib/postgresql/17/data"]
          securityContext:
            runAsUser: 0 
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/17/data

      containers:
        - name: postgres
          image: dhi.io/postgres:17-alpine3.22
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: secuscan-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: secuscan-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secuscan-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: secuscan-config
                  key: DB_NAME
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/17/data
      securityContext:
        fsGroup: 70
      imagePullSecrets:
        - name: dhi-registry-secret
      
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi