apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: secuscan-ns
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS scans (
      id VARCHAR(50) PRIMARY KEY,
      filename VARCHAR(255) NOT NULL,
      status VARCHAR(50) NOT NULL,
      result TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );