apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: secuscan-ns
spec:
  template:
    metadata:
      labels:
        app: db-init-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: alpine:3.19
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secuscan-secrets
                  key: DB_PASS
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: secuscan-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: secuscan-config
                  key: DB_NAME
          volumeMounts:
            - name: init-script
              mountPath: /init.sql
              subPath: init.sql
          command:
            - sh
            - -c
            - |
              apk add --no-cache postgresql-client
              while ! pg_isready -h postgres-svc -p 5432 -U ${DB_USER} -d ${DB_NAME}; do sleep 2; done;
              psql -h postgres-svc -U ${DB_USER} -d ${DB_NAME} -f /init.sql
      volumes:
        - name: init-script
          configMap:
            name: postgres-init-script