apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: secuscan-ns
spec:
  clusterIP: None
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: secuscan-ns
spec:
  serviceName: "minio-svc"
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      initContainers:
        - name: fix-permissions
          image: alpine:3.19
          command: ["sh", "-c", "chmod -R 777 /data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: minio-data
              mountPath: /data

      containers:
        - name: minio
          image: cgr.dev/chainguard/minio
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
          command:
            - /bin/sh
            - -c
            - minio server /data --console-address ":9001"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: secuscan-config
                  key: MINIO_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secuscan-secrets
                  key: MINIO_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
          volumeMounts:
            - name: minio-data
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi