apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-worker
  namespace: secuscan-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scanner-worker
  template:
    metadata:
      labels:
        app: scanner-worker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - scanner-worker
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: scanner-worker
          image: sawyyy/secuscan-scanner-worker:latest
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
          readinessProbe:
            exec:
              command:
                - cat
                - /etc/os-release
            initialDelaySeconds: 2
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: secuscan-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: secuscan-secrets
                  key: DB_PASS
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secuscan-secrets
                  key: MINIO_PASSWORD
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"